name: Build OP Celestia Stack
on:
  push:
    branches:
      - 'develop'
      - 'feat/add_build_push_to_ecr'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: build and push l2
            image: opcelestia-l2
            dockerfile: ops-bedrock/Dockerfile.l2
            context: ./ops-bedrock
            buildargs: ''
          - name: build and push op-node
            image: opcelestia-node
            dockerfile: op-node/Dockerfile
            context: .
            buildargs: '--build-arg BUILDPLATFORM=linux/amd64 --build-arg TARGETOS=linux --build-arg TARGETARCH=amd64'
          - name: build and push op-proposer
            image: opcelestia-proposer
            dockerfile: op-proposer/Dockerfile
            context: .
            buildargs: '--build-arg BUILDPLATFORM=linux/amd64 --build-arg TARGETOS=linux --build-arg TARGETARCH=amd64'
          - name: build and push op-batcher
            image: opcelestia-batcher
            dockerfile: op-batcher/Dockerfile
            context: .
            buildargs: '--build-arg BUILDPLATFORM=linux/amd64 --build-arg TARGETOS=linux --build-arg TARGETARCH=amd64'
          - name: build and push stateviz
            image: opcelestia-stateviz
            dockerfile: ops-bedrock/Dockerfile.stateviz
            context: .
            buildargs: ""
          - name: build and push contracts
            image: opcelestia-contracts
            dockerfile: Dockerfile.contracts-bedrock
            context: .
            buildargs: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: ${{ matrix.name }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ secrets.ECR_REGISTRY }}/${{ matrix.image }}:${{ github.sha }} , ${{ secrets.ECR_REGISTRY }}/${{ matrix.image }}:latest
          file: ${{ matrix.dockerfile }}
          provenance: false
